required = [
  "github.com/heptio/authenticator/cmd/heptio-authenticator-aws",
]

[[override]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.14.0"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/kubicorn/kubicorn"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "k8s.io/api"

[[constraint]]
  branch = "release-1.10"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/kops"
  version = "1.9.1"

[[constraint]]
  version = "v0.3.0"
  name = "github.com/heptio/authenticator"

[[constraint]]
  name = "k8s.io/client-go"
  version = "v7.0.0"

#[[constraint]]
#  name = "k8s.io/kubernetes"
#  version = "1.10.3"

[[constraint]]
  name = "github.com/weaveworks/launcher"
  revision = "4614c4a7368cc77dce1e1da50dd59047b7f07562"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
