apiVersion: skaffold/v1beta4
kind: Config

profiles:

  - name: local
    build:
      local: 
        push: false
        useBuildkit: true
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:local"
      artifacts:
      - image: weaveworks/eksctl-build
        context: ./build
      - image: weaveworks/eksctl
        context: ./
        docker:
          buildArgs:
            EKSCTL_BUILD_IMAGE: weaveworks/eksctl-build:local
            TEST_TARGET: test

  - name: push-any-commit
    build:
      local: 
        push: true
        useBuildkit: true
      artifacts:
      - image: weaveworks/eksctl-build
        context: ./build
      - image: weaveworks/eksctl
        context: ./
        docker:
          buildArgs:
            EKSCTL_BUILD_IMAGE: weaveworks/eksctl-build:local
            TEST_TARGET: test

  - name: local-from-cache
    build:
      local: 
        push: false
        useBuildkit: true
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:local"
      artifacts:
      - image: weaveworks/eksctl-build
        context: ./build
        docker:
          cacheFrom: ["weaveworks/eksctl-build:cache"]
      - image: weaveworks/eksctl
        context: ./
        docker:
          cacheFrom: ["weaveworks/eksctl:cache"]
          buildArgs:
            EKSCTL_BUILD_IMAGE: weaveworks/eksctl-build:local
            TEST_TARGET: test

  - name: push-cache
    build:
      local: 
        push: true
        useBuildkit: true
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:cache"
      artifacts:
      - image: weaveworks/eksctl-build
        context: ./build
      - image: weaveworks/eksctl
        context: ./
        docker:
          buildArgs:
            EKSCTL_BUILD_IMAGE: weaveworks/eksctl-build:cache
            TEST_TARGET: test
