version: 2
jobs:
  make-eksctl-image:
    # use machine build, as otherwise we cannot use make and have to duplicate makefile
    machine:
      image: ubuntu-1604:201903-01
    environment:
        GOCACHE: /home/circleci/.cache/go-build/
        GOPATH: /home/circleci/go
    steps:
      - checkout
      - restore_cache:
            keys:
                - go-cache-{{ .Branch }}-{{ .Revision }}
                - go-cache-{{ .Branch }}-
                - go-cache-
      - run: mkdir -p ./test-results/ginkgo
      - run: make eksctl-image
      - run: sudo chown -R circleci.circleci /home/circleci/.cache/go-build/ /home/circleci/go/pkg/mod/
      - save_cache:
            key: go-cache-{{ .Branch }}-{{ .Revision }}
            paths:
                - "/home/circleci/.cache/go-build/"
                - "/home/circleci/go/pkg/mod/"
      - store_test_results:
          path: ./test-results
      - store_artifacts:
          path: ./test-results
  make-release:
    machine: true
    steps:
      - checkout
      - run: make release

workflows:
  version: 2
  any-commit:
    jobs:
      - make-eksctl-image:
          filters:
            tags:
              ignore: /.*/
  release:
    jobs:
      - make-eksctl-image:
          filters:
            branches:
              ignore: /.*/
            tags:
              ignore: /^latest_release$/
      - make-release:
          requires: [make-eksctl-image]
          filters:
            branches:
              ignore: /.*/
            tags:
              ignore: /^latest_release$/
