# A simple example of ClusterConfig object:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: martina-test-1
  region: eu-north-1

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 1
    iam:
        withAddonPolicies:
            autoScaler: true
            cloudWatch: true
    ssh: # import public key from file
        publicKeyPath: ~/.ssh/id_rsa_tests.pub
