# An example of ClusterConfig object for customizing NAT gateway setup:
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-2
  region: eu-west-1

vpc:
  natGateway: single # valid options are disabled/single/highly-available

nodeGroups:
  - name: ng-1
    instanceType: m5.xlarge
    desiredCapacity: 2
    privateNetworking: true # if only 'Private' subnets are given, this must be enabled