apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    run: dns-test
  name: dns-test
spec:
  selector:
    matchLabels:
      run: dns-test
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: dns-test
    spec:
      containers:
      - image: tutum/dnsutils@sha256:d2244ad47219529f1003bd1513f5c99e71655353a3a63624ea9cb19f8393d5fe
        name: dns-test
        stdin: true
        tty: true
        readinessProbe:
          initialDelaySeconds: 0
          periodSeconds: 3
          failureThreshold: 3
          timeoutSeconds: 1
          exec:
            command:
            - nslookup
            - kubernetes.default.svc.cluster.local.

